### ISSUE TITLE
github.com/ethereum/go-ethereum@v1.13.1/crypto/kzg4844/kzg4844_gokzg.go:52:66: cannot convert blob (variable of type Blob) to type gokzg4844.Blob

### ISSUE THREAD

**Issue by smile-magic** [crate-crypto/go-kzg-4844#54]
error: github.com/ethereum/go-ethereum@v1.13.1/crypto/kzg4844/kzg4844_gokzg.go:52:66: cannot convert blob (variable of type Blob) to type gokzg4844.Blob
version:0.4.0

**Comment by simbahebinbo** [comment]
I also encountered the same problem.
May I ask how you resolved it?
